# Generated by Django 6.0.6 on 2026-06-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_options_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='general', max_length=20),
            preserve_default=False,
        ),
    ]
