# Generated by Django 6.0.6 on 2026-06-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_alter_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
